name: HotPotato
version: 1.0.0
description: This plugin is a minigame called "Hot Potato".
author: TomBom4
main: io.github.tombom4.hotpotato.HotPotatoPlugin
commands:
  HotPotato:
    description: Starts the game with optional countdown.
    usage: /hotpotato <seconds>
    aliases: hp
    permission: HotPotato.hotpotato
    permission: You don't have permission to start the game.
  Wins:
    description: Shows the wins of the player
    usage: /wins [player]
  Teleporter:
    description: Adds a teleporter to the world.
    usage: /teleporter [<x> <y> <z>] <x> <y> <z>